name = "BoltzTraP"
uuid = "cbda18ea-c181-4d25-a1c9-354b8a2900c6"
license = "GPL-3.0-or-later"
authors = ["Hiroharu Sugawara <hsugawa@gmail.com>"]
version = "0.1.1"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Brillouin = "23470ee3-d0df-4052-8b1a-8cbd6363e7f0"
CodecXz = "ba30903b-d9e8-5048-a5ec-d1f5b0d4b47b"
Comonicon = "863f3e99-da2a-4334-8734-de3dacbe5542"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PythonPlot = "274fc56d-3b97-40fa-a1cd-1b4a50311bf9"
Spglib = "f761d5c5-86db-4880-b97f-9680a7cccfb5"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"

[weakdeps]
DFTK = "acf6eb54-70d9-11e9-0013-234b7a5f5337"

[extensions]
BoltzTraPDFTKExt = "DFTK"
BoltzTraPNCDatasetsExt = "NCDatasets"

[compat]
BenchmarkTools = "1.6.3"
Brillouin = "0.5"
CodecXz = "0.7"
Comonicon = "1.0.8"
DFTK = "0.7.20"
FFTW = "1"
Interpolations = "0.15, 0.16"
JLD2 = "0.4, 0.5"
JSON = "1.3.0"
JSON3 = "1"
NCDatasets = "0.14"
NPZ = "0.4"
Plots = "1.41.3"
PythonPlot = "1.0.6"
Spglib = "1"
StaticArrays = "1"
StatsBase = "0.34"
StatsPlots = "0.15.8"
julia = "1.10"

[extras]
NPZ = "15e1cf62-19b3-5cfa-8e77-841668bca605"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "NPZ", "Statistics", "Random"]
